### ISSUE TITLE
Metrolink API change breaking Station Filter

### ISSUE THREAD

**Issue by wordswords** [ayubmalik/trams#3]
Hi,

I really like this app and want to continue using it.

I think Metrolink have changed the API in the last couple of days.
`trams display BMR`

Returns:
`2023/05/24 21:36:44 json: cannot unmarshal number into Go value of type []trams.Metrolink`

`trams display` seems to work to display all the trams, but any individual station filter outputs the same error.

**Comment by ayubmalik** [comment]
Hi, thanks for raising this. Will look into it soon.

**Comment by ayubmalik** [comment]
Hi there, I have update this. Looks like the API is the same. I think it maybe that I was caching the station IDs returned by TFGM, so I have added some code to delete the cache file if it is stale (7 days or older).

Can you build or download version v1.0.4 and try again. Works on my Linux machine.

Thanks.

**Comment by wordswords** [comment]
Hi,

Thanks for the update. I have tested it on my Windows 11 WSL2 with Ubuntu, and also my Ubuntu LTS computers, and it all seems to work fine now.

Thanks!
David
