### ISSUE TITLE
json unmarshaling problem

### ISSUE THREAD

**Issue by wordswords** [ayubmalik/trams#4]
On the latest (1.0.4) version:

```
trams display BMR                                                      
2023/07/18 05:33:02 json: cannot unmarshal number into Go value of type []trams.Metrolink
```

**Comment by ayubmalik** [comment]
I will look into this soon.

**Comment by ayubmalik** [comment]
I could not recreate this locally on my Linux machine. However, I have tidied up the logic to remove caching of some interim station data.

Please try version 1.2.0  https://github.com/ayubmalik/trams/releases/tag/v1.2.0)

If the problem persists, try running with environment variable TRAMS_DEBUG set to 1, i.e.

```
TRAMS_DEBUG=1 trams display BMR > debug.txt
```

This will dump the HTTP responses from the backend to  the file debug.txt, which you can send to me, so I can take look.

cheers,

Ayub

**Comment by ayubmalik** [comment]
Closing, as assuming worked.

**Comment by wordswords** [comment]
Haven't had any problems, looks fine now, thanks!
